### ISSUE TITLE
Exception thrown when closing Visual Studio instance

### ISSUE THREAD

**Issue by KarolAntczak** [Samsung/Dexter#158]
After closing experimental instance of Visual Studio, a `System.NullReferenceException` is thrown: 

![image](https://user-images.githubusercontent.com/13940703/28623481-61f98c1a-7216-11e7-9ac6-e8a364a2e35f.png)

Stack trace:
```
 at Dexter.UI.DexterCommandPackage.UnregisterSolutionManager() in D:\\Projects\\Dexter\\Dexter\\project\\dexter-vs\\Dexter\\Core\\UI\\DexterCommandPackage.cs:line 173
 at Dexter.UI.DexterCommandPackage.Dispose(Boolean disposing) in D:\\Projects\\Dexter\\Dexter\\project\\dexter-vs\\Dexter\\Core\\UI\\DexterCommandPackage.cs:line 167
 at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.Close()"	string
```

**Comment by mdopark** [comment]
This does not seem to be a normal shutdown situation.
A experimental instance for the debugging should be closed by 'Stop Dubugging' button of host VS.

**Comment by KarolAntczak** [comment]
> This does not seem to be a normal shutdown situation.
> A experimental instance for the debugging should be closed by 'Stop Dubugging' button of host VS.

Ok. When instance is closed by 'Stop Debugging' the problem does not occur. 
I am closing this issue then.

**Comment by mdopark** [comment]
@KarolAntczak 
I deleted my comment because I realized that the basis of what I said was not clear.
I think this issue and fix are reasonable.

**Comment by KarolAntczak** [comment]
Ok. I reopened issue and will apply fix once again.
