### ISSUE TITLE
[dexter-cli_0.9.0_64] Connection refused connect. http://127.0.0.1:4982/api/analysis/result

### ISSUE THREAD

**Issue by AlexSangJoonPark** [Samsung/Dexter#19]
I have an error after I executed the dexter-cli for java project.

[ERROR] [2015-09-30 19:38:42] (CliLogger.java:88) - com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java type, class java.util.HashMap, and MIME media type, application/json, was not found : Connection refused connect. check your server is on > http://127.0.0.1:4982/api/analysis/result
[ERROR] [2015-09-30 19:38:42] (CliLogger.java:89) - com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java type, class java.util.HashMap, and MIME media type, application/json, was not found : Connection refused connect. check your server is on > http://127.0.0.1:4982/api/analysis/result
com.samsung.sec.dexter.core.exception.DexterRuntimeException: com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java type, class java.util.HashMap, and MIME media type, application/json, was not found : Connection refused connect. check your server is on > http://127.0.0.1:4982/api/analysis/result
	at com.samsung.sec.dexter.core.job.SendResultJob.sendResult(SendResultJob.java:100)
	at com.samsung.sec.dexter.core.job.SendResultJob.send(SendResultJob.java:70)
	at com.samsung.sec.dexter.executor.cli.Main.run(Main.java:444)
	at com.samsung.sec.dexter.executor.cli.Main.main(Main.java:119)
Caused by: com.samsung.sec.dexter.core.exception.DexterRuntimeException: com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java type, class java.util.HashMap, and MIME media type, application/json, was not found : Connection refused connect. check your server is on > http://127.0.0.1:4982/api/analysis/result
	at com.samsung.sec.dexter.core.util.JerseyDexterWebResource.postWithBody(JerseyDexterWebResource.java:180)
	at com.samsung.sec.dexter.core.util.DexterClient.sendAnalsysisResult(DexterClient.java:262)
	at com.samsung.sec.dexter.core.job.SendResultJob.sendResult(SendResultJob.java:95)
	... 3 more
Caused by: com.sun.jersey.api.client.ClientHandlerException: com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java type, class java.util.HashMap, and MIME media type, application/json, was not found
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
	at com.samsung.sec.dexter.core.util.JerseyDexterWebResource.postWithBody(JerseyDexterWebResource.java:178)
	... 5 more
Caused by: com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java type, class java.util.HashMap, and MIME media type, application/json, was not found
	at com.sun.jersey.api.client.RequestWriter.writeRequestEntity(RequestWriter.java:288)
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:217)
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153)
	... 10 more

**Comment by Min-Ho-Kim** [comment]
Thank you for reporting.

Please use the following command:
```javascript
$ curl "http://dexter-server-ip:dexter-server-port/api/v1/isServerAlive2" -L
```

If you see the following result, please use the real IP instead of '127.0.0.1' in a dexter_cfg.json file.
![image](https://cloud.githubusercontent.com/assets/12783044/10213087/8d8b4c80-6843-11e5-929b-eca624a11ca4.png)

If you use your real IP address, you can see like the below:
![image](https://cloud.githubusercontent.com/assets/12783044/10213136/37ffc7b8-6844-11e5-9747-1109100b8383.png)

If you have the same problem, please, share your dexter_cfg.json file in 'bin' folder.

Let me know the result.  :-)
