### ISSUE TITLE
[dexter-monitor 0.9.2] Cannot run dexter-monitor

### ISSUE THREAD

**Issue by KarolAntczak** [Samsung/Dexter#39]
When trying to start dexter-monitor, following error occurs: 

```
~/dexter/project/dexter-monitor$ node app.js -p=1111

    return key.startsWith('-');
               ^
TypeError: Object -p has no method 'startsWith'
    at isValidCliOption (/home/test.user/dexter/project/dexter-monitor/util/dexter-util.js:96:16)
    at /home/test.user/dexter/project/dexter-monitor/util/dexter-util.js:59:12
    at arrayEach (/home/test.user/dexter/project/dexter-monitor/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/test.user/dexter/project/dexter-monitor/node_modules/lodash/index.js:3345:13)
    at baseWrapperValue (/home/test.user/dexter/project/dexter-monitor/node_modules/lodash/index.js:2768:30)
    at LodashWrapper.wrapperValue (/home/test.user/dexter/project/dexter-monitor/node_modules/lodash/index.js:6124:14)
    at Object.exports.getCliOptions (/home/test.user/dexter/project/dexter-monitor/util/dexter-util.js:64:8)
    at loadCliOptions (/home/test.user/dexter/project/dexter-monitor/app.js:69:27)
    at initialize (/home/test.user/dexter/project/dexter-monitor/app.js:42:5)
    at Object.<anonymous> (/home/test.user/dexter/project/dexter-monitor/app.js:37:1)
```

I'm using Node.js v0.10.25 running on Ubuntu 14.04. 
What can be wrong?

**Comment by Min-Ho-Kim** [comment]
dexter-monitor was tested on v4.2.1 of nodejs.
The string.startsWith() function is specified at ES6: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

I guess the version 0.10.25 of nodejs does not support the new string functions.
But you can try it with '-harmony' option.
Refer to the following URL: http://www.2ality.com/2013/04/nodejs-harmony.html

**Comment by Min-Ho-Kim** [comment]
Also you can read this: https://nodejs.org/en/docs/es6/

**Comment by KarolAntczak** [comment]
Thank you, you were right. After updating node.js to 4.2.6, the problem was solved.
