### ISSUE TITLE
[dexter-cppcheck] Analysis doesn't work if project path contains spaces

### ISSUE THREAD

**Issue by KarolAntczak** [Samsung/Dexter#52]
Analysis of c++ project doesn't work if project path contains spaces.
Example of non working configuration file:

```
{
  "dexterHome": "D:/Applications/dexter/0.9.4/dexter-cli_0.9.4_32/",
  "dexterServerIp": "dexter-server",
  "dexterServerPort": "0000",
  "projectName": "ExampleCppProject",
  "projectFullPath": "C:\\Example Cpp Project\\ExampleCppProject",
  "sourceDir": [
    "C:\\Example Cpp Project\\ExampleCppProject"
  ],
  "headerDir": [
    "C:\Example Cpp Project\\ExampleCppProject"
  ],
  "binDir": "",
  "libDir": [],
  "fileName": [
    "ExampleCppProject.cpp"
  ],
  "modulePath": "",
  "sourceEncoding": "UTF-8",
  "type": "FILE"
}
```

dexter-executor.log contains following line:

`analyzed failed  : C:/Example Cpp Project/ExampleCppProject/ExampleCppProject.cpp `

**Comment by Minjung-Baek** [comment]
Please send to me "ExampleCppProject.cpp" and /log/"dexter-core.log"

**Comment by KarolAntczak** [comment]
Still experiencing this issue (on dexter 0.10.2).

**Comment by Farwaykorse** [comment]
This issue still persists.
With the VS plugin, Dexter does not work for projects with a path containing a space.
The path here would be something like `C:\Users\R LastName\git\cpp\project\...`

dexter-executor.log
````
[ERROR] [2018-03-07 20:57:56] (CLILog.java:154) - there is no file : C:\Users\R
[ERROR] [2018-03-07 20:57:56] (CLILog.java:155) - there is no file : C:\Users\R
com.samsung.sec.dexter.core.exception.DexterRuntimeException: there is no file : C:\Users\R
	at com.samsung.sec.dexter.core.util.DexterUtil.throwExceptionWhenFileNotExist(DexterUtil.java:1214)
	at com.samsung.sec.dexter.executor.cli.DexterCLIOption.setFieldsByCommandLine(DexterCLIOption.java:174)
	at com.samsung.sec.dexter.executor.cli.DexterCLIOption.createCliOptionFromArguments(DexterCLIOption.java:78)
	at com.samsung.sec.dexter.executor.cli.DexterCLIOption.<init>(DexterCLIOption.java:72)
	at com.samsung.sec.dexter.executor.cli.Main.main(Main.java:65)
[ERROR] [2018-03-07 20:57:56] (Main.java:83) - there is no file : C:\Users\R
com.samsung.sec.dexter.core.exception.DexterRuntimeException: there is no file : C:\Users\R
	at com.samsung.sec.dexter.core.util.DexterUtil.throwExceptionWhenFileNotExist(DexterUtil.java:1214)
	at com.samsung.sec.dexter.executor.cli.DexterCLIOption.setFieldsByCommandLine(DexterCLIOption.java:174)
	at com.samsung.sec.dexter.executor.cli.DexterCLIOption.createCliOptionFromArguments(DexterCLIOption.java:78)
	at com.samsung.sec.dexter.executor.cli.DexterCLIOption.<init>(DexterCLIOption.java:72)
	at com.samsung.sec.dexter.executor.cli.Main.main(Main.java:65)
````

**Comment by JanSawicki** [comment]
Does this issue still appear? 
I have just run analyses using Dexter CPPCheck CLI and Dexter VS Extension and both finished successfully (version 0.10.6).

![cppcheckclidirectorywithspaces](https://user-images.githubusercontent.com/29917202/42753092-191963a2-88f0-11e8-9d21-32d849e34f2c.png)
![cppcheckvsextensiondirectorywithspaces](https://user-images.githubusercontent.com/29917202/42753093-194b6366-88f0-11e8-8c05-2bdf4f1474e8.png)

**Comment by Farwaykorse** [comment]
Thank you @JanSawicki 
You are right, it is not the project path. Further testing with a project on a path without spaces results in the **exact** same error and logs. (Showing the same partial path.)

My issue seems unrelated to the original issue.
It is just from the VS Extension where the above error and logs are generated.
Analysis using the CLI command: `.\dexter2.bat -s` runs fine.

My issue appears with any project, and for 'Solution', 'Project' and 'single file' analysis.
I did configure the extension by setting the home directory and selection "Standalone analysis".
![capture](https://user-images.githubusercontent.com/1308320/43980470-81c78d72-9cee-11e8-92c7-f2705a854019.JPG)
